name: Try GitHub Action

on:
  pull_request:
    types: [opened]

jobs:
  try-github-action:
    name: Try GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Use this GitHub Action
        uses: john-d-pelingo/jira-link-issue-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          atlassian-domain: 'https://johndpelingo.atlassian.net'
          board-name: 'MEME'
